Option Strict Off
Option Explicit On
Module DateCheck

    ' ##TESTING Verified working on 03/16/2015
    ' VALIDATES DATES FROM COURT IN THE FORMAT OF: YYYYMMDD
    Public Function DateCheck(ByRef chkDate As String) As Boolean
        Dim bolDateCheck As Boolean
        Dim strDay As String = "00"
        Dim strMonth As String = "00"
        Dim strYear As String = "0000"

        Try
            If Trim(chkDate).Length = 8 Then
                strYear = Left(chkDate, 4)
                strDay = Mid(chkDate, 7, 2)
                strMonth = Mid(chkDate, 5, 2)

                bolDateCheck = IsDate(String.Format("{0}/{1}/{2}", strYear, strMonth, strDay))
                DateCheck = bolDateCheck
            Else
                DateCheck = False
            End If
        Catch
            Dim strTmp As String = ""
            DateCheck = False
            strTmp = String.Format("{0}{1}VB Error # {2}", strTmp, vbCrLf, Str(Err.Number))
            strTmp = String.Format("{0}{1}   Generated by {2}", strTmp, vbCrLf, Err.Source)
            strTmp = String.Format("{0}{1}   Description  {2}", strTmp, vbCrLf, Err.Description)
            MsgBox(strTmp)
        End Try

    End Function

End Module