Option Strict Off
Option Explicit On

Imports Microsoft.VisualBasic
Imports System.Data.Sql
Imports System.Data.SqlClient
Imports System.Configuration
Imports System

Module MainForm
	Public Const strGoodReturn As String = "Good"
	Public Const strBadReturn As String = "Problem"
	Public Const strEmptyReturn As String = "Empty tblCourtRecord"
	Public Const strCaseFile As String = "K:\daily\case.dly"
	Public Const strEligFile As String = "K:\reports\not_elig.txt"
	Public Const strReportsLoc As String = "K:\reports\"
    Public Const strDupsFileLoc As String = "K:\Output\"
	Public g_dtmRunDate As Date
	
	'UPGRADE_NOTE: Main was upgraded to Main_Renamed. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="A9E4979A-37FA-4718-9994-97DD76ED70A7"'
	Sub Main_Renamed()
		On Error GoTo Err_Main
		Dim Casenum As String
		Dim c As Short
        Dim x As String
        'strReportsLoc + "SessionInfo.txt"

		g_dtmRunDate = Now
		
        'FileOpen(3, strReportsLoc & "SessionInfo.txt", OpenMode.Append)
        'FileOpen(3, OutFl, OpenMode.Append)
        Const OutFl As String = "D:\Temp\TssData\SessionInfo.txt"   ' "K:\reports\SessionInfo.txt"
        My.Computer.FileSystem.WriteAllText(OutFl, g_dtmRunDate, True)
        'PrintLine(3, g_dtmRunDate)

		
        x = CourtRecord()
        My.Computer.FileSystem.WriteAllText(OutFl, String.Format("{0}NewCases {1}", Space(5), x), True)
        'PrintLine(3, Space(5) & "NewCases " & x)
		
		'UPGRADE_WARNING: Couldn't resolve default property of object NoPrevious. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
        x = NoPrevious()
        ' My.Computer.FileSystem.WriteAllText(OutFl, String.Format("{0}NoPrevious {1}", Space(5), x), True)
        'PrintLine(3, Space(5) & "NoPrevious " & x)
		
		'UPGRADE_WARNING: Couldn't resolve default property of object AddCases. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6A50421D-15FE-4896-8A1B-2EC21E9037B2"'
        'x = AddCases()
        'My.Computer.FileSystem.WriteAllText(OutFl, String.Format("{0}AddCases {1}", Space(5), x), True)
        'PrintLine(3, Space(5) & "AddCases " & x)
		
        'Call ApplyUpdates()
        'FileClose(3)
        'MsgBox("Add New Cases Process Complete")
		
Exit_Main: 
		Exit Sub
		
Err_Main: 
		Dim strTmp As String
        strTmp = String.Format("{0}{1}VB Error # {2}", strTmp, vbCrLf, Str(Err.Number))
        strTmp = String.Format("{0}{1}   Generated by {2}", strTmp, vbCrLf, Err.Source)
        strTmp = String.Format("{0}{1}   Description  {2}", strTmp, vbCrLf, Err.Description)
		MsgBox(strTmp)
		FileClose()
		Resume Exit_Main
		
    End Sub


End Module

