Option Strict Off
Option Explicit On
Module DateChecking

    Function DateCheck(ByRef chkDate As String) As Boolean
        Dim bolDateCheck As Boolean
        Dim strDay As String = "00"
        Dim strMonth As String = "00"
        Dim strYear As String = "0000"

        Try
            If Trim(chkDate).Length = 8 Then
                strYear = Left(chkDate, 4)
                strDay = Mid(chkDate, 7, 2)
                strMonth = Mid(chkDate, 5, 2)

                bolDateCheck = IsDate(strYear + "/" + strMonth + "/" + strDay)
                DateCheck = bolDateCheck
            Else
                DateCheck = False
            End If
        Catch
            Dim strTmp As String = ""
            DateCheck = False
            strTmp = strTmp & vbCrLf & "VB Error # " & Str(Err.Number)
            strTmp = strTmp & vbCrLf & "   Generated by " & Err.Source
            strTmp = strTmp & vbCrLf & "   Description  " & Err.Description
            MsgBox(strTmp)
        End Try

    End Function

End Module