Option Strict Off
Option Explicit On
Module GetFiscalYear
	'Public Const connect As String = "Provider=SQLOLEDB.1;Integrated Security=SSPI;Persist Security Info=True;Initial Catalog=TSS;Data Source=TssQry"
	'Public Const connect As String = "Provider=SQLOLEDB.1;Password=*39l*27;Persist Security Info=True;User ID=x7xgblk;Initial Catalog=TSS;Data Source=TRASQL" 'Data Source=64.107.133.22"
	Public Const connect As String = "Provider=MSDASQL.1;Persist Security Info=False;Data Source=TssQry;Initial Catalog=Tss"
	
	Function FiscalYear() As String
		On Error GoTo Err_FiscalYear
		Dim cnn1 As ADODB.Connection
		Dim rstFY As ADODB.Recordset
		Dim strSQL1 As String
		
		cnn1 = New ADODB.Connection
		strSQL1 = "Execute [GetFiscalYear]"
		cnn1.Open(connect)
		rstFY = New ADODB.Recordset
		rstFY.CursorType = ADODB.CursorTypeEnum.adOpenStatic
		rstFY.LockType = ADODB.LockTypeEnum.adLockReadOnly
		rstFY.Open(strSQL1, cnn1)
		If Not rstFY.EOF Or Not rstFY.BOF Then
			FiscalYear = rstFY.Fields("strYear").Value
		End If
		rstFY.Close()
		cnn1.Close()
		'UPGRADE_NOTE: Object rstFY may not be destroyed until it is garbage collected. Click for more: 'ms-help://MS.VSCC.v90/dv_commoner/local/redirect.htm?keyword="6E35BFF6-CD74-4B09-9689-3E1A43DF8969"'
		rstFY = Nothing
		
Exit_FiscalYear: 
		Exit Function
		
Err_FiscalYear: 
		Dim strTmp As String
		strTmp = strTmp & vbCrLf & "VB Error # " & Str(Err.Number)
		strTmp = strTmp & vbCrLf & "   Generated by " & Err.Source
		strTmp = strTmp & vbCrLf & "   Description  " & Err.Description
		MsgBox(strTmp)
		Resume Exit_FiscalYear
		
	End Function
End Module