Option Strict Off
Option Explicit On
Module InsertCases
	
	'**********************************************************************
    '*  This Function uses a class called DataEnvironment_TssDb           *
	'*  The connecition must be define for each site. Parameter int1  is  *
	'*  passed to the Server Stored Procedure: ic_InsertCases             *
	'**********************************************************************
	
    Function AddCases() As Integer

        Dim de As New DataEnvironment_TssDb
        Dim intCode As Short
        Dim int1 As Integer

        Try
            int1 = 0
            de.ic_InsertCases(int1)
            Debug.Print("intCode Value: " & intCode)

            If Not int1 = 1 Then
                Debug.Print("We have a problem Houston!" & intCode)
            Else
                Debug.Print("Everything is peachy." & intCode)
            End If

            de = Nothing

            AddCases = int1
        Catch
            Dim strTmp As String = ""
            strTmp = strTmp & vbCrLf & "VB Error # " & Str(Err.Number)
            strTmp = strTmp & vbCrLf & "   Generated by " & Err.Source
            strTmp = strTmp & vbCrLf & "   Description  " & Err.Description
            MsgBox(strTmp)
            de = Nothing
        End Try

    End Function
End Module